linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gofmt
    - goimports
    - gocyclo
    - dupl
    - unconvert
    - misspell
    - gocritic

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
        - staticcheck
        - gosimple
        - unused
        - structcheck
        - varcheck
        - ineffassign
        - deadcode
        - typecheck
        - gofmt
        - goimports
        - gocyclo
        - dupl
        - unconvert
        - misspell
        - gocritic
    - path: ^protobuf/
      linters:
        - typecheck
        - govet
        - staticcheck